### ISSUE TITLE
能增加一个用于主动触发刷新得函数吗？

### ISSUE THREAD

**Issue by Hades-li** [baoolong/PullToRefresh_Flutter#2]
通常列表在页面加载进来的时候都会主动触发刷新事件，此时只能通过函数来调用。这个需求还是很重要的。建议增加。

**Comment by baoolong** [comment]
OK  ，这个可以有， 新版已经兼容了IOS ，可以先用着哈

**Comment by baoolong** [comment]
OK ，这个可以有， 刚出新版本了，新版已经兼容了IOS ，上下拉分别可控，可以先用着哈

**Comment by baoolong** [comment]
已经添加 请看0.1.9版本，触发在initState方法里面我注释掉了的那部分
