### ISSUE TITLE
这个文档写的 小学生写作水平？

### ISSUE THREAD

**Issue by nigelly** [baoolong/PullToRefresh_Flutter#7]
首先我不是针对你，既然作为开源库，就要本着对大家负责的心态，这样出文档，有意思么？

**Comment by baoolong** [comment]
感谢您提出的宝贵意见，非常抱歉文档对您引起的不适，我也是去年刚用git，所以很多东西不熟，等我有时间会改进的。如果您在使用中有问题的话，可以qq联系 ，或在issues中提出你的问题
